language: node_js
node_js:
  - "6"
  
branches:
  only:
  - master
  
cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - npm prune

script:
  - npm run test

notifications:
  email: false